const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const LIKE = 'LIKE';
const FETCH_ALL = 'FETCH_ALL';

const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';

const AUTH = 'AUTH';

const LOGOUT = 'LOGOUT';

const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING';

const FETCH_POST = 'FETCH_POST';

const COMMENT = 'COMMENT';


export { CREATE, UPDATE, DELETE, LIKE, FETCH_ALL, AUTH, LOGOUT, FETCH_BY_SEARCH, START_LOADING, END_LOADING, FETCH_POST, COMMENT };